forgejo_admin_user: ENC[AES256_GCM,data:YenXuquu72UXQA==,iv:DqWwltfMLG0fXrMQQ0ymeBG0l7gqF2Lce7YwGTZ4yos=,tag:BXxAS17oQHMTD0RP1tgKEA==,type:str]
forgejo_admin_password: ENC[AES256_GCM,data:q6n918dPC1SeXYbDsrJXUfRCp5fFbg==,iv:n25wr5eRpxeWEgNiKENuMB+LMoo2mQPup84x3o5f5vQ=,tag:COoXqYSHG6eBH9rvus8F6w==,type:str]
forgejo_admin_email: ENC[AES256_GCM,data:gVFPY0IaiLGb/BVAmQ==,iv:z7658TEFAO1vMSU/qGYJwWYaYO2PXc78CN0PmYIWjFg=,tag:qGB3Fu0dWiP39Sszp3aVWg==,type:str]
forgejo_claude_user: ENC[AES256_GCM,data:olXKfwhz,iv:vvDtAG77FXBLuU7XbMcik6rNdGvRzxI0qKKQHNZl04s=,tag:yQ84Dt11L1fL0OqovSL5mw==,type:str]
forgejo_claude_password: ENC[AES256_GCM,data:jO6emogeUpJLuS0Of8WJ1j/5iJCzSA==,iv:Oc10FMuzfvEECy9Nra2XEnCjJcnCT1IuSMx8FQoJ/xA=,tag:DzLL8NOHFSp3QYgpt8R7Rg==,type:str]
forgejo_claude_email: ENC[AES256_GCM,data:VJ+bF2x+bCTrslA/ors=,iv:bVQFFGhG+DzHkfzO+m8m1lpeXQpYSJ1y9ZDzwoM688I=,tag:ndldHrR4nZoU7u8zdd/4WA==,type:str]
gitea_admin_user: ENC[AES256_GCM,data:KmGoGyrO,iv:B/+MtGZjt4XUeCF6o3OGSORb0LBwif3ShReykjIYBoo=,tag:NcyKjpsrxQd4HF0qKr3YDQ==,type:str]
gitea_admin_password: ENC[AES256_GCM,data:whffVfK4C5TTS4i4Z74YK7sKYWF3Lw==,iv:PD1CbfGuPKCe+W+LF8GZR9H4aQh/knyoSY8Nl0Q76/U=,tag:OZMsbJ/wl+OOKMiWAyM36g==,type:str]
gitea_admin_email: ENC[AES256_GCM,data:JrT3TSAn4tf1xPfW0A==,iv:aaxa1jaSu2Gpe0SWeSZsz3PQkMx6ChvAZluA6VHAYT4=,tag:eLBrUeAc32cOK7WSHsoQJw==,type:str]
gitea_jade_user: ENC[AES256_GCM,data:ci1O2Q==,iv:mDG4QBOJla+GdCn7KDlRYWr9YN8416fdINV/FCBAFTU=,tag:KrZ5YJsXlQOrBni431cPXg==,type:str]
gitea_jade_password: ENC[AES256_GCM,data:dJp0FlL7rOWPob3ExzWD9G1W6iGWgA==,iv:3HBcgUBBElQZqYGrbafmAaAlWBohgMLQWVLDKlKc+Vg=,tag:unYyMYy0igU9SeAapdDLqw==,type:str]
gitea_jade_email: ENC[AES256_GCM,data:4SDNOlWfY8hyn88C,iv:9g2fHDTMa6+S5yXiAQd6scOmOYK9ZSkAgUd/XYi4Dbk=,tag:SRK1dQiMsT1jmrsFB2t1Zg==,type:str]
mcp_claude_knowledge_token: ENC[AES256_GCM,data:sDDMno6DsmZ5vEJvVa2eaRR4ARhFEUmcpNPCM0ng4zcu9IfKsltPX7nGTvvG03iSU5QO,iv:jm5KIXJtyDsiR/aPfx3BoyhUxEaEec3hPjdCxA53XXE=,tag:Bl25fRqc8BSgGrp32Cgawg==,type:str]
mcp_claude_journal_token: ENC[AES256_GCM,data:GGvYLZv656EQtG3yDP0vMQudhPzl8tL+1CWeHpuBOuvs45YanKZyXcwWNs3wU68KMKQB,iv:Le9oqfFj0ECsKVUH9yl6RlpTXidGEcRdmVMxAyYRDUs=,tag:rSBv0Mk1xCyc3iKuSFnktw==,type:str]
mcp_opencode_knowledge_token: ENC[AES256_GCM,data:+f7uKporj2fLWOJhl9e84qcjYXqqzNouYSL2ytwStxVGQr1CwY8SVv2KS1/DEEbD0oEa,iv:dCOenk4WAOs4UwC8O12EeIWW6QdNP3F0pPFW7hHUIXY=,tag:KGoAEhbMhPHKzBVcqFbIKw==,type:str]
mcp_opencode_journal_token: ENC[AES256_GCM,data:ge+dgocy7WChGXTq/ZaVS4+2+jNH6TLGv7V6Ur+TQCvO5Jxx3YIltZAu3JpBumMc8aSx,iv:4lmP2tloUEp+e5KHB6ZZ4H+Yl1w1lkXfRUzUjDQrhj8=,tag:Cu6tspnLp+1T1PHNm672dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL1Z2c3c4NDBEcFE0OWEx
            OUNkNlFuOEE3Wi9IK0ZWSGxpNWtuTmI5dWlFCktjenVON3Y2eGNpS0YxRWVKSUt6
            YVZOai9qT2NYR241Mk9HbHpCc1FueU0KLS0tIFZhMXNFcFdIYkR6eW05cU9RNDlH
            cm1Vd1owYllsZW9rampzNk5Idjc3YWsKYWrZuNd1cpLc0wGFI4VRRE5JwFVOHRvr
            Hn6tbkSk+8ohO5/QsYWskH0b8cdLPeHOxSqw2V6FqQQOh/kWfqrWvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T11:08:34Z"
    mac: ENC[AES256_GCM,data:BgO5B8+M2xiXIQazDOwAzp85jWTxXH7v5w6fYOmGs19q+Jch3LM10cRqpczAqpJ7KKOYntuIXoJVhGONEhN3uC4Hvk97/JMUrDzspOTq6cwKDbrXUyARqWQ5xTIQPnaLDIbJrjhAfhcCWgnCZVxJ2ObXad+DHXppukRgRho227k=,iv:3Wj6fezWgFojhQC0Ymd4I1u+oEqbZd1SvizsNpTDgWU=,tag:ZQNdmAra3yHEdyMrf0h9kA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
