forgejo_admin_user: ENC[AES256_GCM,data:rVA7QpB0DzRtlA==,iv:5U7ZdNdj20EFKHmiTmGxtSi2/Ve82+uitkSK+GyCk5A=,tag:KOzAznSq6KEJLRMkxCRDsw==,type:str]
forgejo_admin_password: ENC[AES256_GCM,data:pxU8lWQ/gOJ/yOpqGvgCN/3JT9MNqw==,iv:m5xMxFi6eqcPU4hMU9neuHAMMeZB93xUnllJmgdHQag=,tag:oxW9CqbsCtos5z8RIJoCZw==,type:str]
forgejo_admin_email: ENC[AES256_GCM,data:Tc4GiPpKEl5BLlmXQg==,iv:HvG8yeVcEicBGCcwASJyaG600SrOnfP5gMRz08Vku5I=,tag:Rn6mgxvym66aUOcbUhgtHA==,type:str]
forgejo_claude_user: ENC[AES256_GCM,data:l/aCzza+,iv:XHBKKAytIGhwJAw3c+tnGEC11aYBeafj7YGoDS3Higg=,tag:Tva+cd6WGB1MCifbaPx24g==,type:str]
forgejo_claude_password: ENC[AES256_GCM,data:aM8QLoXdzUbUxjncXMw+ZyJCNUtr8A==,iv:Mey4QzbM4ibhbkV2WuYm2hZhgCgH7fq1NeeUQEl2j6c=,tag:f1X0LD3W+HdlZGjLhpjpzA==,type:str]
forgejo_claude_email: ENC[AES256_GCM,data:m8POaMndWxQXuUIeol8=,iv:7tPzhTBQqAAc0WPJu9Ne2h2DYTtfnfYxLCXlOKOVhJU=,tag:u4BqxvOCbtuQPXXB4wDZsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVUdNZ2E5MFBDdnpLcGRG
            czVnUW9EcktZSzJPcVhDSjlXaGpMNkZ3K2hvCjJsRnRzcDMzQWNLY05hN3R3OGY1
            TXduYncxL2lBWGV3Z0hMcmJYQTVzTVEKLS0tIE1WK0tJaEduOG9xSERtS0lOMnRN
            ZFgxRjQ3VGo0WHNLMUhYb2lTZXBTRFkKk/RUsaSJjh10PBHRij42PY/mfz03ZGiU
            91X+o2b3um3h6b0WI3KQBPc144u+nXGD6mMX67ge6faYyWMyJGgNKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T21:55:49Z"
    mac: ENC[AES256_GCM,data:jXXytYERQXA5YczU9t4E1VtdefP5eVVFBoX9gCNYj9Rz05OhI7iRboiPQBIM77ztN/jGrqxdCwgjzfUY/8H9SiPZCzmZosUqbB01LVt8bzWdjjO5HFIxzSDNEywaTaaW+u/VZDlSqhpSd8mcSMl02caVddl6rEpecVvBQn6FkkY=,iv:RyoLzMHIYKYjnHItsPgfhUpdMCanbLZI6W7CyahlXbU=,tag:+3kBlhxYXXDayqjlYiXDMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
