forgejo_oidc_client_id: ENC[AES256_GCM,data:I7makd71wR2+upYtN1eLF9dgvayh9mY+InO2kXo8IbXBuJnZ,iv:HbLmho4jGonAiN7f7wB5RpO8oDtJ3qg6kW1QBFtD72E=,tag:emrg7K4U7g56pRmy4ubuoQ==,type:str]
forgejo_oidc_client_secret: ENC[AES256_GCM,data:x7BdNbflcr/JdrWDPtbVc+98f+uf28VbDtKtZ49bMrM=,iv:jTwPfotfvby5wHD0E+xcS6Y4/P7HU4eL/wg1wDT5sMc=,tag:vR2VB3vFrKNp1cfsY+RVMg==,type:str]
linkding_oidc_client_id: ENC[AES256_GCM,data:dYYCYjWMPArD4Y2tboaSHAB0RnX0/rQqH+AIeMpMDSErtaaS,iv:c8par1PpbP40Zq9m3Xl39m3RC8a8oje08ZG2bPYMwCk=,tag:bXXErfDvtHMUDR5DvhhrPg==,type:str]
linkding_oidc_client_secret: ENC[AES256_GCM,data:R52b70kYJYkHlGJkXBObDSPR2iVyoqraQjt2q97MUB0=,iv:7naDF9DJEOhSU1pn6cSaUhU1y2MpyefIECUm3elcKZo=,tag:wv4zR4FTCZd/L9TZbctzog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aWlBby9ibDRrUlBxZEpZ
            OGt6RTYweHBnbmloZzlxaUR4QTJhcXZpTDJnCkVqYlJ6M0pMWklMd2NYc25oNzJY
            ZWp5RktHVDdOTXE1akNuUmoyMW5kNUkKLS0tIE5nZE02K1B2QjBZSmVjNlBhamVX
            ZHNMaDNwZGt1MnllRU9NTlJOREFOdHMK2kAoCkH0stR83Fi+qPBpyPdbHGTDExB0
            ZdPdcwkm+DzZZu/tN/8w3jIjDNBugJp5X6yVSDrP6jsOCn9seqvVug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T14:26:39Z"
    mac: ENC[AES256_GCM,data:VNohxWX44lhtsCQQmjwJNyVmfLns+qVCcSo3IcSIgANYc8w1KOJki+fMLawhzCNSz87/NAgPz9ffclqexTiCUAV7cA9YMGLTkAFfT02uzncMEo6qpPVU9ETMpG6/3XE5fha051WnCIoXGJpI4+e6fnhL0sepRYVPyOSGEt/WTso=,iv:rmzq+I/OGaSOy+SXLMy/TVmuKzDUgzFO5IA4OQs2TgQ=,tag:dnhsu/frmoCTka3pTo8yxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
