b2_account_id: ENC[AES256_GCM,data:gYidbJqgdOAjdrXkwIPMHlLYRzxhIPUUcA==,iv:PUfO/e8g9tMEx6MHUi2oD49oC7HqErScEC57wNKR2gU=,tag:cCq2RBq7mEjKPmoeoRLI+g==,type:str]
b2_account_key: ENC[AES256_GCM,data:p2pMBsv0eUpxC4JsOoUQNdWWmI/xQLXHnoqTKElXbg==,iv:4RNKtGFwjkMEOJUg01xeVvYoLwm0XfXZ3uope5AmuIE=,tag:6unwYj+WBytF8QCdD/ogQw==,type:str]
b2_bucket: ENC[AES256_GCM,data:SHxYcboTGYBE5+CZyQQAoJxkpQ==,iv:foBCbcMZOTx6Ju58yyPFjgihJ/prwaD1ORgNWOjanJ4=,tag:+a4hROCApnLmSNAY6UBqww==,type:str]
restic_password: ENC[AES256_GCM,data:NIUaIQvoyocI6bI5qTLhj6KvWe04Hi29wetALqJq7rnDjhDwykwW1SC8ni1hh9NfvDSJVm6gqxFusS9MEA+QmA==,iv:meNgnwuxfo22qFMsCoYWblCRcq7dA6hs4hI/dfJ/Sx8=,tag:2j7vXY6zEXs5EhvDrnZxPw==,type:str]
healthchecks_url: ENC[AES256_GCM,data:mcpdUnKcbljdpO/gUPZivrY9faGQMOCp5MevXVQ+0EkczfV1dA+hcQ3wJ+R5XBnDaabdui5CGNw=,iv:xuQfWmZn07X/s/162neXFLAze8P7zUnc28ddYDjs29Y=,tag:lBs+59HWvAzJ5paZkNF2Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZk5iSFBkR0MyVGR4Z0Vu
            cjArK0hWM3lmdWFPazRmK1hFRE1XWThTVzNRCmVTQ0JKU2t6dVBwOFBmblBQWldD
            bGNlUVFTcVdCNGF1RndwSUtkZ1RtTU0KLS0tIGJtVW84R2tkWGxJaVdSTmMxUy9k
            Zi9sT3VCbys0cmwya21rVFdWZDIxS2MKo+h287IbaVzz/hvaL8ITvBHPrH5s4GbQ
            Exu+RXoPCqP6WEpFtGb0eBRxT6+HTK0W9krstaZJ0Jgm6mYWRKYRgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T21:17:15Z"
    mac: ENC[AES256_GCM,data:srZAxgFx/JaDFkv4D8exuzFnhuRokwOXieo8C2tm+P3fNvxDqtwHpIiFBA1yhW1qufx6j5q0C1y5kCA5FvC/2MFshadicijQcL6JSDoipicCfyQo4rEkTxGYgfDJehUu7SyY0kbFlcHlDQO00Yl7vPdQTxI+W02UFiXrsYWKwoU=,iv:fJfjnCKDKYSEn0Bue5GqYKEYKcwT9dQVekeq+1JBkus=,tag:X8T6s9wnpP/U+xzLhj7/5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
