seedbox_host: ENC[AES256_GCM,data:y0tMKL9iyV1WqN313SQ=,iv:5wLzrW6u9zUFkYCze9QLkiXZu8BqMhW43gYlF/REedQ=,tag:Ri4zBefEEHfEo8Ax02KieA==,type:str]
seedbox_host_key: ENC[AES256_GCM,data:zOJMWx4uNJ3ybQibshQxXdjVIZbsQNMobhbF5uV3SuX0rtlGpuL8+BfReAR/449c1SQ3nscNqlkqsF521Lkx437ChToK32KIvCxtlUliTr1oN8fB8Rr6LF+gO5T3gJE=,iv:9+WfwFFKUVG9hbHdOA/+bvotZSBd6TCMgw6jHEq8CF0=,tag:mT6ISv+/YdrtO/rH6gZfqQ==,type:str]
seedbox_port: ENC[AES256_GCM,data:kGA=,iv:osoS46We49HSpRluAzRWkHrKX12ydbwYE6DWd1kM+Gw=,tag:v4/sgm+z7QnoJgqkmvxAKQ==,type:str]
seedbox_remote_path: ENC[AES256_GCM,data:12vLMP8aQn7Ep2O80aqehzFDN6zE4z3t800rYuoy5D7A6smZ9ByyYQ==,iv:WyYqR5wZoSpbA0o6WVSn1s7NSxxZJTP9wM51aPhUiCM=,tag:SOzkJPQmOHsmZctDnRqsaQ==,type:str]
seedbox_ssh_private_key: ENC[AES256_GCM,data:gdBAJygV2aqQo6DegWbxxPQzQsGc2XJw1ykc7Yqnbk+VcOxn5s6ux6HT7ZBYGLG01I6k6CouSneW+KIMndlo2tdvTYA/4DmeXdDhKDdEZqUOGZy0xb2VB7RQPbn3fTWEXvGqKMakEr6o7+z+ceDWpeGX3D3jIstn0nyKDfXilYN4hn99j+CeQl7BfkcTB7s+CEQFj3w6Roap5uOq1bs1yQGh7ganUtFRmL6urMHsiL/Z7JvA3zzOZQ8EtH7JJnwupfJhtgamhalyhAKOb4bDqHAXRL0vLWvVkcFNA8idJB35QjdYbGfQeyGbHC4/jmAJ7pVptSIbj53OQ+3VWutEgmifCRDZqW5DrnCPeImO6ulpjNjR/TYknyaZ4n7XAMm9FSUQGwmKvCkhGXT62K5RNUGCW0aV0Kii6MtIsMIR68qzyKoQ0aKRw/fAfbIrHlrfqhlkzSgCzhF788PeaPPzPj3qoG/+MO0iEq22DVAOpSUVuknU2eJ8zuhskqBvYsEmPblbc2JXkW1AH6P2k3McH3p3B2eqg3qFdDPo,iv:Jh6PB9O1Y8kq/ABpcNTgO91y4Fq+Q021cXkxRkbNJi8=,tag:JCJ9KgeDEdGsKBMsErC/lQ==,type:str]
seedbox_user: ENC[AES256_GCM,data:t870/u6WIRBS0QeZ,iv:yI1x/R/qypjdrryqhiExbF9hIObJWu2oQxWyFoW8LLc=,tag:idZw8asMI9K3l75R8a9n/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb2lKc2k3b3FjdmoxUFB2
            TjN0Ui9RQUhRa2ZtTnJaejR5TVZiMnRVSkFRCklneWhXbkJ5bTBCaHJJTDZiZFhv
            Y3JGTnlzRGN2VlR6bGQrSnhUakx5ak0KLS0tIFc0QjJWQ002aU5FeGhBRUFKaHBN
            MDlsNGZWUURFdk53R0IzZm41SERuaFEKFRMPFtmbGbhAXDc9byBHgmqRbK+BhjId
            IQcgMJpdBm38RT7FacptliNIzxEwnLCKMfzcEr7ZEXdk1Fxc9cKlpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:43:53Z"
    mac: ENC[AES256_GCM,data:p44868BHipwWeDZQztGgqo6sr0urtn0lPyaOQYGO13CrJ41rL7ZIDGeaNsubgYWd+N433b/Ec91BG4iTTBb6YeONXGZ4bXZFVeO2MaWdB07poHBRaq7IhXkrfSlrfAB++Ce/FIy9Qqrk+lfEyGLv1ExSeGD+bDcGw/Vk2Xp0LMM=,iv:jzebXisYAdLCYRFcGa0N7nz44QKhXAyIQTqm4bvitsw=,tag:jbblKr6l1FKUkvpBZveQhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
