seedbox_host: ENC[AES256_GCM,data:hJ9no9lZ+6Ryjz06HT0=,iv:4rLPiFZTTebIHmAl0iyvG/yfa4sCCUgT2joNHqJUrZw=,tag:55H8HkzCv8Xvqgpy7e7esw==,type:str]
seedbox_host_key: ENC[AES256_GCM,data:V0pzS3RWKqdvykcWv1Q3U+wubAnOaGBjombOoaSeOeq4LVBva07RmxQHYeu2K1ztz7eR/PrxFVomcJLmLYR7ef/S+m+bA0B9+rIlCCH8+knkNhXU1xJ7M1zJUHf3FWM=,iv:FhExl2BQvyX7AOcUB82OnQQXEzib0Asyae74ALsaa+8=,tag:+4e0WmOn8pUE5jJrKprFmA==,type:str]
seedbox_port: ENC[AES256_GCM,data:hjs=,iv:QsBJEDkGOM4XnF91sPNfvFttFtzeYMYh8urC/vrglCA=,tag:addb8WLSf88+xkZTe8gu5g==,type:str]
seedbox_qbit_password: ENC[AES256_GCM,data:x9AQ09+J26qrYLvyxvk=,iv:K0w+wS5EkFfmAkSALsoU+M37XHW0Inqj3G0oqBMlocY=,tag:j78sBvkT/OVuqF7JVSqx5w==,type:str]
seedbox_remote_path: ENC[AES256_GCM,data:PDD+IvsLevtTG5LXkFBtodaEkprGnrgSZCSJ7p1/VJbzX03o+DLaYQ==,iv:S1N2CzAzsPP5yvNrwkxjDtUXYRLEGunFLqaXn1SBEhc=,tag:wMXgp3/RgZyKZGlDiiYpSw==,type:str]
seedbox_ssh_private_key: ENC[AES256_GCM,data:u3Bo5cBU8fE6rV4RD7aX2m6AEtYPQWMb4jEbj5jVZfIGU8PAy1SVtHamK9bknYYForpUfEUy4fAPBuByfsnnzEDC6Eh7xLWqS8d+4Rb+JOgPFt9YAAphx4blBnpaN4RMRAr9LOT6DpqBOfE+GNfYUL2ynlVjjEdG92W/R8NhUhFvsE/zbSAtUpd+hYTwQ4Y71RLNsh6P5tT+Hzs622Uh8dE5hDuEncwN9zoGqu6qBYC9nKhtUIq9yPY3O7qYMSXPncmVz7kQjrq6oNyRsB34Pi0INCdG+W9KAfMPDFyth/1weLc//mGZaD+n44v6REpMb9MBruS5Ak0+QmVOR4oC8Zi7e5wlWU7ch5032u1K7zw83kxwBhEqudvTQ8rrnNQmWFCxHUhZ/BG8k1KJKIa4iQ8J2LGKteqHsWQpNvErtXibbD4uf0PbKgYburTo1LK/OA+U6CtIMDv1ZhJ0173rAFEmBdh3vXMEgVrwJXDGSSaNN9YvEAP3B3ojGH/NPuzzjuCKc1QcgfahLZY9xYcxAiUjQ26tebw367i4,iv:3wT3/4y+D3N6cgOVKVeZF+JY3hzUkHPBZoXtDie977k=,tag:qGw2na8BLOviXDhUdZ1k+Q==,type:str]
seedbox_user: ENC[AES256_GCM,data:cz/NQ1zGOyLnOgNI,iv:wTGPCD1OTST+PxwOhve5znKJfkNXQSDr+5OfThM6dPY=,tag:UZRb+3+qzuIMT2ja1glbUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTnBSWW1xWjc0MmdKaGlO
            cVpxRVlERU9aRzBqWkV3RmxxZmo3ZCtmK0hjCjBPYng3MkdDVVg1ZjdjVG5QTXdF
            OXlXc2dDV2NCOVc3L015Ymp2ajM0NWcKLS0tIGYwM3JtRm1CbmRXSUZONkYrU0NV
            cDV2WmZiVmZGL0ZIY2l6VHo2ZjRzUlUKyVaDCg0Off6q5wBaz/boercaMHMfsPDF
            QsoDyVjKonPQ2zE5BzFM/MC46wqTeQSuuVNj39HLbD8IMtHj9uWDfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T09:10:19Z"
    mac: ENC[AES256_GCM,data:qVOgHxV/zydK1GJbrKHXo77T60jKECnoBVsVq6bAhjXWcNB6Ux+0abtU1BLsb0TeAlcbpdK3+wyxUAwq6J/Wpr9r/w0nqvnskX4uFUAG0vZtjsAyL/Pm17tdDer67qG/Pvn0mHP3lgoxbABvw7UsvvAE7hY5Ejp16f/vLjqmbcI=,iv:jkoflyncjupPx0bCLNPP/F3Ea8WirUnqyH2Hr5+odl4=,tag:NbTJ17mlVXnOwUt+1agDCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
