seedbox_host: ENC[AES256_GCM,data:mPk+S0Y6QwonwtxFMFI=,iv:9ciMTlVuU8b6KyhrD5jUGfCf2ML/dlT2p96Z67YTonE=,tag:ZQsB/Epww/qX+56oqbCyoQ==,type:str]
seedbox_host_key: ENC[AES256_GCM,data:p0C9RYaposwBYMwmjQGk8lMWF0NR6t51TwMgwL2T/e3tiiJbk2ohVJsn/6bqIw306bGn9bvYWEzyuLaCEbz5SWhHFmAv8aGoQ8tzostmynESisl6sTkWibJ18ZIvb/4=,iv:bOq0ERIQDhHRXbRZeRHeSDsC4UhLI5+iV9Grl/QgDAU=,tag:Cb74eMrFcLpgQh5OzStzow==,type:str]
seedbox_port: ENC[AES256_GCM,data:cNE=,iv:uSzEmY7tgWmdDhXE/ru+A2/n6fB6aVjO5i+OBGlPfdE=,tag:NN4RIbhOsKLVB4Aw/4FZ9g==,type:str]
seedbox_qbit_password: ENC[AES256_GCM,data:jgG5WKU/OKcWRwSRLWUSwg==,iv:SNPKydtMC7DuS7JEYtfQvj97m45LtIkcGBcJyodlxlw=,tag:65FgKBRyqwDgsY50iy3VUA==,type:str]
seedbox_remote_path: ENC[AES256_GCM,data:flUjD3IeloUhVrXQjo4I4CWV6ZHEKYogQS7GTJ9DivVe+JegONK0wA==,iv:zNxOhqmt1qdzPwiVDwrYXXy5sSjwWfE+sMUU7vM69N4=,tag:fl6OwNKLF1LMS+NNJ6/ODg==,type:str]
seedbox_ssh_private_key: ENC[AES256_GCM,data:/SoJhLjMrqHYLEZpiAV3a0PC6uOlcOLkIDGTeLK0C6bwXEEmIHYV/4aHUawC0kvZcAjwA2O6JMisyiT/sNByrEhDLt+N5m8Txg8FeGn/a17dZ9RB/V6PowN62GjadPUnA7ebhGcz5YahbBeddw9Zm24BvPeuV4/Ev1dg+KtvHyLmOO9RKFJmttn9KuMHz20gy6QBrzh4KvkE4+wMrfx3J9VllWCVuyP8vBKmdEfdUiuoQtB2OfYZxcrM9ywtubS3FUGZOIy2tEZH+UZVpkh7lB5c62fmUYBwf+i+kirJAG7dQZ/OB8bMbmcAjAvR5EoV2JcvPdRnuQvn0paKhE5AxcpQ/DOnjoAPhaiR4I/ds+mu7ZT0mGq+RammqbeKdRxtOaN+vHZTGJgYJKSZ3ZYA4tBkzWp6NiRIhV69HKaZYCH8TKbteWtgcjAmiHQfZw4LR0Z+ZlXNR3YeP7heuxqCG6GCR4cv/HAtyeKRgz5DW+6oqPDrroo8F6Kufrfg+lnSX84Gvqb7dAUyMzmRLVbe4mTbw9hbFOrP3nAT,iv:j3vOErrETezoHxGoaWjIM1A79Q0jRn8NSNqF9lyrCnk=,tag:Z8UNA71tURe2SwTa8x1mmg==,type:str]
seedbox_user: ENC[AES256_GCM,data:nHd/M7OvnPufhflW,iv:gh2PwIcW1O+tCh7iQzUzXoH6cZ0cTLeJdQhNl6kYVx0=,tag:gKoIXU7fnBRBU2lAV1XrcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRXNSN3plNW5HejFsZENp
            STNoelQrVUlHaDF6WDk0UzBqaENCSWNmRzJBCjRhbzR3V2pYZHlwNU5EOE1vOFFz
            aTBKOWZ3MGdmSUJiNXlYY3RUZG1uQ2MKLS0tIDNkbjFYZng0dGtpSUJFQ0NIZmcw
            T2tReXUxbENYcTBseFRxb2d5dVFLS1EKwI+1OHAqSSN97AFzuo/vrMxrUH+R0OHW
            2q7RoZJwD1a4EhHuJbJiXx/gT4eygE3qpetXwT/G3+G2RxtrvQyKsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T07:32:51Z"
    mac: ENC[AES256_GCM,data:CZjkPPicrw3Q4aQ5PJcp+d7OX1qfJxrNr07zZcgiHQm2crjcdFIANpyKoS5QOKnYrYWPhZLT4bb8osJd0XBOD4lWI1OU2j39Ui/u+1FTwOwshRckJKBC6oH9smj1HImA7TL6ZPpmJLViXGd0D6VPZW+So0v++q9jtRxZuxP2slU=,iv:ON8+/gP1W6Sd8IXGmEUCBSMif5d3Tms7H1SfayzdqXM=,tag:zjiO0tg4v+ldHDlp2OL+SQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
