samba_password: ENC[AES256_GCM,data:BT/JOlhvSVKWL3579iYNHrOnAQVjityp,iv:X7DVvPK4NTY6X/IXi94Hs0TTOXCU69cdP+IdTL6r80s=,tag:eUIyKI1ahnt+0AsqyDi63Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUkh4WGo4aTJmOXdvZmgv
            S3B6VE13NU5qUW85TkVYZFhiQ1lqZVZsL2tBCkhSL1REcVNkdzR4OG9SbEoxWDN5
            ZGZKbXMwYnRDNTA2OHpaaWlYaFlBaUEKLS0tIFRHbnEyQ2I0MWZnbEs5TlUraFlj
            NGhwYVdwZk5vd3JldUs0K24yZ2FhaEUKEjvJPxal3xnADMuzKYTKXlnvwXEn5XqB
            l40Nmiyk7vNbGZSXqUAuL7FZ9EWCPteeirlmmQekCvwk3lAos3b+RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T22:52:58Z"
    mac: ENC[AES256_GCM,data:lpycf+KYdjn1LKudArBrBMoDi86nLLbwawBzZyqnU46D85ZmiL5HiM9b3+bnC8086gSA5X9k2YY9mTYG4HDeTSo5GsfG7Dch6WnlStezRX3dCyDhl7d9iydZrFanjV5ZlMyDazSOuH0bWZ7+gl7o4JFLX4ifmxMSIC4unPtDjSM=,iv:KqTa4XIv2sZT/SYfpard8hom+M7Seyffv68sETHL+/k=,tag:Jln0skruW2DJT3Zau04Z0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
