#ENC[AES256_GCM,data:UKCbqymPKUsVSTWqUJiZqT1Lcgut/HoiYC9xYkjwhukQK57rnoOvSbA43XoDLRa61RNGJ9za2MZ/yg==,iv:XeYrCb1acRBkt66b/X8MN87XjHx44raL0NgReg/SDU0=,tag:f5UH9f5rupC3iNDqn7TwQQ==,type:comment]
torrentleech_username: ENC[AES256_GCM,data:FRWZUvOVxdOyDw==,iv:SfCXgiQ0eRSks9fRGbsBKCGPAp3adKYJNg9ekpgb4p4=,tag:pfpk/Fg3KGBOK7tYklIhnw==,type:str]
torrentleech_password: ENC[AES256_GCM,data:34oO9Bzkrcm9P5ePNzWFr+ykWaKUCW//dV3TtI/sH+UD7oFl6F7/Gk4A8szminl67keKNEG8zwtV+CV9wMLQiw==,iv:kxXLoF1iNxYQFVM6jq4gNplcHLV/gm2daSYWgD00IMo=,tag:TqzYYx3J6pptXp3/0PSBqw==,type:str]
torrentleech_rss_key: ENC[AES256_GCM,data:gx8DKa5xpVrZHC+ofFX1BB/yGac=,iv:ZjqQofzGNVCVHXWIzHBfvezoLwObEIRzJcP7QyNZom8=,tag:rA2Pr3bImWLBgcEf6eIcRQ==,type:str]
torrentleech_irc_key: ENC[AES256_GCM,data:ZctRQ/q9XRGGFexf4X8vxEMInik=,iv:rZ3HyWk3u0WVWonv2T78RlHeH6lxgVYrodEHmhhBou0=,tag:h+7oeJ9LLMQrjHgqWWbJEA==,type:str]
torrentleech_irc_nick: ENC[AES256_GCM,data:QlrDHJMhmSrXTgb6t9A=,iv:Av9TEVjYb76aktOdswJ5a69J2tf4siK3ntLxZ607Iho=,tag:BH4+fERC5/tg6ubFMJG7lw==,type:str]
fearnopeer_api_key: ENC[AES256_GCM,data:FRlRPUTrYzFKj5q5lDeVm4zOn2ZVdMSXElEDfg8E+g7CNjZmpoS8M0qg1DN8F2V517FlDeRBDGJjSpTtJAnNM1vWpn2gRVplLjJg+HtzrPuNyxLGfASj0ci+mH4kV/+5xEf7/w==,iv:PwAri8KeLdKY1qSHG9NlzuoOxmFeIMqCUhuhXrlIrjA=,tag:SYZ7qeeSewjDrnglKbOjIg==,type:str]
fearnopeer_rss_key: ENC[AES256_GCM,data:NjEE68pjJpn1RNG2PQ27RQdiW07dKIhsTTESbxRl2PI=,iv:0lFES+TabIjqrQfRkGbI5lpKuyQrTac/XF2aovoa9Lw=,tag:Pzlrbc1x8cFBOUSO36CDNQ==,type:str]
fearnopeer_irc_nick: ENC[AES256_GCM,data:L99aItfPHfEBolXqeYAc,iv:xsEl1JXUGEfesWFWYF8Jc+EFYveNJ+ajtJHFS5z7gZc=,tag:nLRjDM/QjNblpwwqr60qkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTTFqczdUdGRpVjZCaFlk
            V2hqckVBbmRYUUc2N0ZpRExIdDV6NlQvbDAwCk1iZjE4emMyemYrZHJvSUlXUkpG
            WjlmKzZmbVJ4dVdyMm9GQXlqSDdYZkkKLS0tIGVScVNNb0VGVWNXd214NTR6cFVh
            YmlIOGY3NGFSbzRIdnF2VEM4VWJ1L2cK8d49on98pVO+ctTSJN8mSsP9ndQU5Qu5
            5dufaTF+foCuk1wf1CcO/uQIqKennDC+kkvJgs3tGoKGTiMKqR7UXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:55:39Z"
    mac: ENC[AES256_GCM,data:LuQYHpi6broY6qYpagR9kOus0swecD7EFRYu4igN+kEJWTLcFThC4eE+eu8Gl27/SpuBwOZetOAJQRJlQOqpC9xs3T8WKq5VI5muK3cGloZWFtSJhwk6JT+ZX2CXAsbAIBdnOWP5P94nBCh7QOweuARiHu+7mzIeEGxsHzQFRGM=,iv:EcQc5kGYurnjAetQ8p7I3RDbV4qTbY1n5sP58n0OJUg=,tag:2MJaE52N3P7zPP4wpi5alg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
