proxmox_admin_user: ENC[AES256_GCM,data:O0wRli45vi5scz6e+w==,iv:JRkEFSx1NJNrjBWrZ0G3EJO0gjBA5ha/MHOxKEAF5xM=,tag:MqKygwSJec7LjDPK48XV5w==,type:str]
proxmox_admin_password: ENC[AES256_GCM,data:1HxwXN/CUZVGXjZKEWA=,iv:iJF/5GbWJctTeeMXEQKfxVqxuMjtMRVLwMKA77xckYE=,tag:kOTtcMR+GrZwmB9zAdYa/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTklZRFNMbUpYb0k0Q203
            QkRCL1NXWEZSSmZJUncyY1p3WGlDUVl5OEdJCjZFaXdpYTk2MitEZGx3amdtVzRi
            T3llU2ZON1FyMmRjbStheEJSNlRxOVkKLS0tIGcvK1lBTHJnM2dKbmlBdmszNjBF
            VnNLRStOQzVIU3o2R1p5Kzd1QThZMDgKlc8uUkhmoOUVG4Xgti7SKjP+bdeN9WT1
            U5Zd/jL8eXQBQdqwMaiggjgaZMxB47h/YstY4IFCsvyjoglv9sZRKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T21:21:55Z"
    mac: ENC[AES256_GCM,data:xDNLUAFkTridSz+rzVX4W1dH0bRR8N+6IWvRpNmSOxthdglIPIaF6GyE5KkZcioiGFLNBt39E9vwxhqpH1bpzEh1Crx671MMOP/TK8X0xeilP7+WTSE2ElMRICL3/iQalYSlew62UP8vj/+hwyzV0WrUZrQQFPzChLchxHbs0xw=,iv:PeaO8rjhPySAsry6XX0dqWGDeKXvdiqdV9UYhxquB3I=,tag:zs6fJRRnqBa3zftM9BJgsw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
