all:
  hosts:
    proxmox:
      ansible_host: 192.168.0.158
      ansible_python_interpreter: /usr/bin/python3
    docker_host:
      ansible_host: 192.168.0.159
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    jade:
      ansible_host: 192.168.0.160
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    pandora:
      ansible_host: 192.168.0.161
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
