log:
  level: info

runner:
  file: /data/.runner
  capacity: 1
  timeout: 3h

container:
  docker_host: unix:///var/run/docker.sock
  network: host
  privileged: false
  valid_volumes:
    - /var/run/docker.sock
