domain: ENC[AES256_GCM,data:y5eSz3VoQg==,iv:QE/8W0K7i+poD+2IrNAXbAPPjMTGsCxfg0PyA+hjoqA=,tag:xGcXNaaJHghe+yLxTZDOdA==,type:str]
arcane_encryption_key: ENC[AES256_GCM,data:oEARQjobNoN9bnB58mJ5e2PsqNZ4epEg1w2/XQ7dJyGd4RgOWGj0pB7L7zi6Eb4rlbioPPdW7eNVifuJ1rvwTQ==,iv:CHnxTC0+J7TVDV4W/fhuD4YjIkF05R27fdCOHP6brd4=,tag:9NhcW9CpCIHsAOXofcNXZg==,type:str]
arcane_jwt_secret: ENC[AES256_GCM,data:ohaTNFt29oZxs+bZxoVkrc4quBehTlM36PBFBiQdYHo+4YM8autCEGNemgR+RSGd5Qj/fivwbOSHgf7KYjtW4A==,iv:GvrAy32o5Ep62F53UboXraaPLRUYJx2cUNdG6LVfM2g=,tag:iDfgd2Y/AVgTlr/fsY7WcQ==,type:str]
arcane_admin_user: ENC[AES256_GCM,data:matKmU+SMor9s50=,iv:k4LK6Mq9PVV7HqKySg4HZtfwe92wmslOhRveImHa33w=,tag:GegIgD6GcDOCTOGOyqw0CA==,type:str]
arcane_admin_password: ENC[AES256_GCM,data:jNjWlQ2pM0uavWvC6txDql0cl4i953NLsmof/nc0eBOBuhpYOZbMFWdSpY0fyYlc4cznDNmok5awN3+iyDVNfw==,iv:gVIj5XANtW4aSZ5N+FgwAjYjfoCuB+Kzi37mPDWzSM0=,tag:8wCTI1+o+uXE3v1gLIZkFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM0tNbFp2K0ZhU2FmS1Mz
            KzMyWVZwM3A4cTExYTVlZ2lVNXBlMStpQnhZCjY1M3ZVTThNQjZrQm1DN1ZJK1VE
            UTJTQWQxRDQxWVoxVXcxS3VKb3F0MncKLS0tIFUrN3N2anQ2NEJubHpBZGxCaHB4
            Q3NadkZrRlhtVEhEZjdLTlJ3WnBEUmsKjpwpibK93I/Y3m2NMoYISyC2uihsAX+u
            3NTH91yHNIwNfTsvSbfJlJrT5Nl5q3a4UHNnMIne9V9dO1FXIUW+OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T21:25:44Z"
    mac: ENC[AES256_GCM,data:DqB9XXYC0/c436hqFa7Y23WyiV1b+LINj5Q84uoSDKSAEsY2R0V0zVzUBqflpmTXR80MwHH3heP4hAh/J+z8VdKzkp8gcV6HffLpLnBymAwOVKfXOKLM+MdSs0anZBoevrmzF59mG3/bJdAvgovtaWccTsg+BzXLmyeX52jbJWI=,iv:SwzWDet+bHZS4cjaaPmzzy5OZKQ9DROCqgZWMHYIVc0=,tag:6Ksok20Jxti8MZNQPDasYQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
