arcane_admin_password: ENC[AES256_GCM,data:SpfS+5OjCafs16yn/TzaGeoj8n9Dk+nxk/SavHAbJmdOAO/n6CkEaBeQZlpri9JBQknApi+S+L5Iw1ghNqCoIw==,iv:l7865HM4Zid/NPY1vdR4DMXImXf6EQsEFUOzx1Xmm2A=,tag:QeZ6Ji88ix2h1qj36mWA8g==,type:str]
arcane_admin_user: ENC[AES256_GCM,data:gi/8UCykyYpi9cs=,iv:w65Wsj3m8N6Q8td6FiJw7M95NfH5eymYrWWA1ouK+Ck=,tag:W72rSeAi6R9nltBjcP4SyA==,type:str]
arcane_encryption_key: ENC[AES256_GCM,data:WOki+Mgxk2XtCfMbUIt9yOOgtD72MbkHB30vdYBRnbcgqhC2xjNy6Uq4VzsW0ewUNFahdA7kpsdUzgdsOGmmAA==,iv:zz8f74nhHjI6ZpVwNLeQpUeX0B9/nMH2e2Zya21IN2U=,tag:1ZyHKeNvL7w+vSm9MNvDcQ==,type:str]
arcane_jwt_secret: ENC[AES256_GCM,data:qVzpL7Ool+n9TyfCdJLTKqAGglpxA12cj1/er+o78M/DN4M+bzyfy8SmpdxGWHOz2TRK1DNpPyAGTVrjU5sFjw==,iv:nWi9z5yyzmxR9ksXgBaobWwt4wqQMkZSH0U5McoMYHs=,tag:oy8qtcSZBORExnX/yK/b4w==,type:str]
autobrr_session_secret: ENC[AES256_GCM,data:PrvorUzK0SLu09/i6hL7/hQ6wyxsLwBYjIUWT1EVyqw=,iv:UqLFiQlkMaA5CbFbL/ekLMM+AbYGzskF+SvEMRsHvDw=,tag:z9t75qvoDqnZVn0rInYC4g==,type:str]
domain: ENC[AES256_GCM,data:jMQ3YqK0qQ==,iv:lVn95Z/v9qF1sBQkGowwMl1w2SIsa3LMs/tnoGyYThE=,tag:TtzGnk8m5UkNjYUVRlteiQ==,type:str]
jellyfin_admin_password: ENC[AES256_GCM,data:YT6Am2XXblWhDJG2YNKsQYPl5Y7de1WkGwHmJqh5D1z5LMoXSyqbXH3hAd353tUYX4wE1PL5O/vQlxQ7/UPk3Q==,iv:alpsIJ8sWkr17UReU69Guv71WywH/oz7kGY90F+drbo=,tag:a51GsFeGeRa1zfXY7FjF5Q==,type:str]
jellyfin_admin_user: ENC[AES256_GCM,data:/7rxZz2tzet8Fuc=,iv:1xYnRwoxzSF03YRChp/oXNo5h2P7dsdSs2LToN7Jric=,tag:PAWpCEi6JY8HMXFbd6jTIw==,type:str]
jellyseerr_admin_password: ENC[AES256_GCM,data:LqMyI80yHHmNt0mBoMnrQKXAJSNdK89wsgOj3QT+ZIsZRrg7hebj3+T32NElcJ+zxjU7hC7fIO43knmjIsv3Rw==,iv:6BxA7XDLK5Qc//P4M+vbT6jz7s38WrEpMTycVCx/NSg=,tag:el39Y4B3r103mw4WqlrabA==,type:str]
jellyseerr_admin_user: ENC[AES256_GCM,data:V6AsaVNRC5NjaA==,iv:iD+hqNpsdecpRk+ZFIkPYOh88YaUNlUJFfRE8GOPmYw=,tag:qdwDogqZXGiOH5irXqOVgg==,type:str]
lidarr_api_key: ENC[AES256_GCM,data:R5+jpT/Fjjlsxsq3Mcu4W2duzJy9mmRUa08Ga3mwp3g=,iv:9eVIje5pFLQsKbqX+cfYS56kDrdcAo/TDReHqRUgpzI=,tag:gbxKpBkEFfhl0gx/y9gM0g==,type:str]
linkding_superuser_name: ENC[AES256_GCM,data:YOW1HHzp86c67Q==,iv:obDRSciRL/YHhSx6I/GFwpcXATTu6BlEkEWzEZj1Jk8=,tag:qDPkCY0VFYtFZEd9dWweVw==,type:str]
linkding_superuser_password: ENC[AES256_GCM,data:/braqK513fcbCafbmDKZsQXCibNyuyBdbcKgamy77Nlr+REJqeN0ET0Az/eEuuAck2dDev1ttrtHnZwzHh4zoA==,iv:xJTmFf9qXtLgp1fyPp2i7n8J/Ts8zJX2wBrKsB0ytz0=,tag:0Yyqv7cMLib7XaBiBmdTEA==,type:str]
prowlarr_api_key: ENC[AES256_GCM,data:76QdPRsE4loHNvfFzHTUZAtmaV+SjaDs6Ux4Z/A7wbI=,iv:c50iTv/KkLF7elnaJ6d+dkoqN7+55I2p7xTQqkOSC24=,tag:H7lb+JpN08cKrFLF5j1OkA==,type:str]
radarr_api_key: ENC[AES256_GCM,data:X+Mb40SvkGvZub14hHI8iyrPOncBR8FcG5iwum8Mywk=,iv:bSPOd2FuzI2gaBZ91T3Pw4UV86xdMTWn6lxIZVhF74Y=,tag:7iKHO09jKf7aqJNKm8Dmkg==,type:str]
sonarr_api_key: ENC[AES256_GCM,data:GRpbi/fTY1NI+xsZDRlC1SpjlD5K96vaz1RRNNvk3TI=,iv:Cyfa7fXIIFsFeNEZVSNjCUUxk30malk6juIy00rHGDQ=,tag:++nCxAJivosejrEVKuABUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hxq9k30age89dnn9z8e5pmsd28936gxvv5tmqur87l2wmeg2qg5qr5x3ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQUcwSHdZbzRGNk1WV3gr
            WXZRRDVxRFNJSXQ0b2RsM0RhZXpJMTk0WVI0CkNGYjNUbjNlQ2ZOQWk0OERFTndE
            OEhVR2d1TExBTUcrcFNoMzRPRmdJRlEKLS0tIHpwSjZyL2xYUHlySUJFUVdUbHZv
            bjhBRU1ETXJya1YrS0JtUEt1TndWbXMKPDaGfyEEqO+5OWEdCxCdHVTX/ROzBLJc
            Tbv+DGIOa+7Wplw5J9I/fXL70vXS8A7gi9m1WTFDRPMloSBw+l0Prw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T09:56:34Z"
    mac: ENC[AES256_GCM,data:e+ACGvULQZrJ9LIiAJiQwIpkR5n2o+tMTCVIjT5MZSRcZl1aYrn4aq6OoU4z2q6zAoknhT05Qg5Yc22ynVHTWAzsDGRUgD2OLHEAkm/AwJXN8QWocBrBjE0yoCudC7cY4IuPA9dqq5FTp3d8XRbAmV4d/LjnPZrL7/crGbZpoNs=,iv:wpXD0BTXhiHfJCeN0L1381ht1jr/Dx5apFOee5wFC+U=,tag:3yRfKI3hogo3+jCeFxRYHw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
